include("low_frequency.jl")
include("resonance.jl")
include("self_coupling.jl")
include("angular_dependence.jl")
include("parity_mixing.jl")
include("unequal_frequencies.jl")
include("convergence.jl")

low_frequency()
resonance()
self_coupling()
angular_dependence()
parity_mixing()
unequal_frequencies()
convergence()
